export const UPDATE_CLIENT_ORDER = "UPDATE_CLIENT_ORDER";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_POST = "UPDATE_POST";

export const INIT_PRODUCT = "INIT_PRODUCT";
export const LOADING = "LOADING";
